# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/jtag2pt_jtag_axi_0_0.xci
# IP: The module: 'jtag2pt_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag2pt_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/jtag2pt_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag2pt_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/jtag2pt_jtag_axi_0_0.xci
# IP: The module: 'jtag2pt_jtag_axi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag2pt_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/jtag2pt_jtag_axi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag2pt_jtag_axi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
