# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard_master.xdc

# XDC: imports/Downloads/Nexys-4-DDR-Master.xdc

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# Block Designs: bd/jtag2pt/jtag2pt.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag2pt || ORIG_REF_NAME==jtag2pt} -quiet] -quiet

# IP: bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/jtag2pt_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag2pt_jtag_axi_0_0 || ORIG_REF_NAME==jtag2pt_jtag_axi_0_0} -quiet] -quiet

# IP: bd/jtag2pt/ip/jtag2pt_clk_wiz_0/jtag2pt_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag2pt_clk_wiz_0 || ORIG_REF_NAME==jtag2pt_clk_wiz_0} -quiet] -quiet

# IP: bd/jtag2pt/ip/jtag2pt_rst_clk_wiz_100M_0/jtag2pt_rst_clk_wiz_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag2pt_rst_clk_wiz_100M_0 || ORIG_REF_NAME==jtag2pt_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/jtag2pt/ip/jtag2pt_aes_reg_0_0/jtag2pt_aes_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag2pt_aes_reg_0_0 || ORIG_REF_NAME==jtag2pt_aes_reg_0_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/ila_0/ila_0_ooc.xdc

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/jtag2pt_ooc.xdc

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
