# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.runs/synth_1/tdc.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.cache/wt [current_project]
set_property parent.project_path D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  d:/prj/vivado/ip_repo/aes_reg_1_0
  d:/prj/vivado/ip_repo/axi2pt_1_0
  d:/prj/vivado/ip_repo/axi2pt_1_0
  d:/prj/vivado/ip_repo/jtag2pt_1_0
  d:/prj/vivado/ip_repo/aes256_key_reg_1_0
  d:/prj/vivado/ip_repo/aes_pt_reg_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/vivado/aes_test/aes_test.srcs/sources_1/imports/crypto_src/aes_core.v
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/vivado/aes_test/aes_test.srcs/sources_1/imports/crypto_src/aes_ks.v
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/vivado/aes_test/aes_test.srcs/sources_1/imports/crypto_src/aes_sbox.v
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/others/debouncer_trigger.v
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/vivado/TDC/TDC.srcs/sources_1/imports/src/delay_unit.v
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/tdc_src/priority_encoder.v
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/vivado/TDC/TDC.srcs/sources_1/imports/src/tdc_core.v
  D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/imports/vivado/TDC/TDC.srcs/sources_1/imports/src/tdc.v
}
read_ip -quiet D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

add_files D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/bd/jtag2pt/jtag2pt.bd
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/constraints/jtag2pt_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/constraints/jtag2pt_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_jtag_axi_0_0/jtag2pt_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_clk_wiz_0/jtag2pt_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_clk_wiz_0/jtag2pt_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_clk_wiz_0/jtag2pt_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_rst_clk_wiz_100M_0/jtag2pt_rst_clk_wiz_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_rst_clk_wiz_100M_0/jtag2pt_rst_clk_wiz_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/ip/jtag2pt_rst_clk_wiz_100M_0/jtag2pt_rst_clk_wiz_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/bd/jtag2pt/jtag2pt_ooc.xdc]

read_ip -quiet D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/constrs_1/imports/constraints/zedboard_master.xdc
set_property used_in_implementation false [get_files D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/constrs_1/imports/constraints/zedboard_master.xdc]

read_xdc D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/constrs_1/imports/Downloads/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files D:/prj/vivado/aes_tdc_50_50_artix7/aes_tdc.srcs/constrs_1/imports/Downloads/Nexys-4-DDR-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top tdc -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tdc.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tdc_utilization_synth.rpt -pb tdc_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
